#!/usr/bin/python
#+
# Test application for my xdg_base_dir library.
#
# Written by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-

import sys
import os
import xdg_base_dir

if len(sys.argv) != 4 :
	raise RuntimeError("usage: read|write config|data|cache path")
#end if
op = sys.argv[1]
type = sys.argv[2]
path = sys.argv[3]
if op not in ("read", "write") :
	raise RuntimeError("op must be read or write")
#end if
if type not in ("config", "data", "cache") :
	raise RuntimeError("type must be config, data or cache")
#end if
if op == "read" :
	if type == "config" :
		result = xdg_base_dir.find_config_path(path)
	elif type == "data" :
		result = xdg_base_dir.find_data_path(path)
	elif type == "cache" :
		result = xdg_base_dir.find_cache_path(path)
	#end if
elif op == "write" :
	if type == "config" :
		result = os.path.join(xdg_base_dir.get_config_home(True), path)
	elif type == "data" :
		result = os.path.join(xdg_base_dir.get_data_home(True), path)
	elif type == "cache" :
		result = os.path.join(xdg_base_dir.get_cache_home(True), path)
	#end if
	xdg_base_dir.makedirsif(os.path.dirname(result))
	open(result, "w").close()
#end if
sys.stdout.write(result + "\n")
